name: note_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0

  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  provider: ^6.0.5
  url_launcher: ^6.1.14
  file_picker: ^5.5.0
  uuid: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Ranade
      fonts:
        - asset: assets/fonts/Ranade-Bold.otf
          weight: 600

flutter_intl:
  class_name: GeneratedLocalization
  enabled: true
  main_locale: en
  arb_dir: lib/src/common/localization
  template-arb-file: intl_en.arb
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false

